### ISSUE TITLE
User API code refactor

### ISSUE THREAD

**Issue by xxnpark** [wafflestudio/SNUGH-server#69]
- [ ] 쿼리 최적화
- [ ] 중복 코드 제거
- [ ] View 단순화, Serializer 이용

**Comment by jaejae2374** [comment]
@xxnpark models를 한번 보고왔는데 abstract model을 적용할 필요는 없는 것 같습니다. 상수 정리하고 모델 재정의만 해줘도 많이 깔끔할 거 같네용.. 그 Class Meta에 있는 unique_together은 요즘. 잘 안쓰고 constraint를 쓴다고 하니 아래 링크 참고해서 변경해주면 더 좋을 것 같습니다..! 참고 : https://velog.io/@kmnkit/Django-모델의-Unique-데이터-만들기
